# Generated by Django 5.2.6 on 2025-10-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndfapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='great',
            field=models.BooleanField(default=False),
        ),
    ]
